### ISSUE TITLE
Blank Backup Location on startup

### ISSUE THREAD

**Issue by mreed72** [seadoggie01/CacheBox#3]
I found that if you leave the backup location blank and click "Save" it continually throws an exception because the BU location doesn't save.  I would suggest setting a lookup for this on the Save button click event.
![cap01](https://user-images.githubusercontent.com/2036298/49233208-1d407e80-f3bb-11e8-8916-175fa27d0134.png)

**Comment by seadoggie01** [comment]
Interesting. That must be only if you haven't set a backup folder yet, because it works for me. I'll try it out!

**Comment by mreed72** [comment]
When I first cloned the project and debuged it for the first time.  I did not see a way of "setting" the backup location other than typing in the location in the textbox and then clicking save. 

What i did was leave that textbox blank, then clicked save, and the exceptions started.

**Comment by seadoggie01** [comment]
Thanks! This should be fixed now. Also, I added a tool tip to the backup location folder to help users realize to double click (Should've done that before! :D)
